version: '3.8'

services:
  templateDB:
    container_name: template_db_container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./template-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=T3mpl@t3!
      - MYSQL_USER=template_db
      - MYSQL_PASSWORD=T3mpl@t3!
      - MYSQL_DATABASE=template
    ports:
      - 3306:3306

volumes:
  template-db: